name: Deploy to GitHub Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

env:
  NEXT_PUBLIC_BASE_PATH: /nuraweb

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: 'npm'
          cache-dependency-path: 'package-lock.json'

      - name: Install dependencies
        run: npm ci

      - name: Fetch posts from production API
        env:
          API_BASE_URL: https://lynzm5kprh.execute-api.ap-south-1.amazonaws.com/prod
          API_STAGE: prod
          ADMIN_USERNAME: ${{ secrets.ADMIN_USERNAME }}
          ADMIN_PASSWORD: ${{ secrets.ADMIN_PASSWORD }}
        run: npm run build:posts

      - name: Build with Next.js
        env:
          NEXT_PUBLIC_BASE_PATH: /nuraweb
          NEXT_PUBLIC_DEFAULT_THEME: "dark"
          NEXT_PUBLIC_API_BASE_URL: https://lynzm5kprh.execute-api.ap-south-1.amazonaws.com/prod
          NEXT_PUBLIC_SITE_URL: https://arunrajan6600.github.io/nuraweb
        run: npm run build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: out

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
